parameters:
#    salon_admin.example.class: Salon\AdminBundle\Example

services:
#    salon_admin.example:
#        class: %salon_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
